// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type PreGoAccUserBase9999 struct {
	UserID         int32
	UserAccount    string
	UserPassowrd   string
	UserSalt       string
	UserLoginTime  sql.NullTime
	UserLogoutTime sql.NullTime
	UserLoginIp    sql.NullString
	UserCreatedAt  sql.NullTime
	UserUpdatedAt  sql.NullTime
}

type PreGoAccUserInfo9999 struct {
	UserID       uint64
	UserAccount  string
	UserNickname sql.NullString
	UserAvatar   sql.NullString
	// 0-Locked, 1-Activated, 2-Not Activated
	UserState  uint8
	UserMobile sql.NullString
	// 0-Secret, 1-Male, 2-Female
	UserGender   sql.NullInt16
	UserBirthday sql.NullTime
	UserEmail    sql.NullString
	// 0-Not Authenticated, 1-Authenticated
	UserIsAuthentication uint8
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type PreGoAccUserVerify9999 struct {
	VerifyID      int32
	VerifyOtp     string
	VerifyKey     string
	VerifyKeyHash string
	VerifyType    sql.NullInt32
	// 0-No, 1-Yes
	IsVerified sql.NullInt32
	// 0-No, 1-Yes
	IsDeleted       sql.NullInt32
	VerifyCreatedAt sql.NullTime
	VerifyUpdatedAt sql.NullTime
}
