// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoCrmUser = "go_crm_user"

// GoCrmUser Account
type GoCrmUser struct {
	UsrID             int32  `gorm:"column:usr_id;primaryKey;autoIncrement:true" json:"usr_id"`
	UsrEmail          string `gorm:"column:usr_email;not null" json:"usr_email"`
	UsrPhone          string `gorm:"column:usr_phone;not null" json:"usr_phone"`
	UsrUsername       string `gorm:"column:usr_username;not null" json:"usr_username"`
	UsrPassword       string `gorm:"column:usr_password;not null" json:"usr_password"`
	UsrCreatedAt      int32  `gorm:"column:usr_created_at;not null" json:"usr_created_at"`
	UsrUpdatedAt      int32  `gorm:"column:usr_updated_at;not null" json:"usr_updated_at"`
	UsrCreateIPAt     string `gorm:"column:usr_create_ip_at;not null" json:"usr_create_ip_at"`
	UsrLastLoginAt    int32  `gorm:"column:usr_last_login_at;not null" json:"usr_last_login_at"`
	UsrLastLoginIPAt  string `gorm:"column:usr_last_login_ip_at;not null" json:"usr_last_login_ip_at"`
	UsrLastLoginTimes int32  `gorm:"column:usr_last_login_times;not null" json:"usr_last_login_times"`
	UsrStatus         int32  `gorm:"column:usr_status;not null;comment:Status 1:enable, 0:disable, -1:deleted" json:"usr_status"` // Status 1:enable, 0:disable, -1:deleted
}

// TableName GoCrmUser's table name
func (*GoCrmUser) TableName() string {
	return TableNameGoCrmUser
}
